TecWeb/Models/Aluno.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace TecWeb.Models {
    public class Aluno {
        public int IdAluno { get; set; }
        public string Nome { get; set; }
        public int RA { get; set; }
        public DateTime DataNascimento { get; set; }

        public Aluno(int idAluno, string nome, int rA, DateTime dataNascimento) {
            IdAluno = idAluno;
            Nome = nome;
            RA = rA;
            DataNascimento = dataNascimento;
        }
        public static List<Aluno> listarAluno() {
            SqlConnection minhaConexao = new SqlConnection(ConfigurationManager.ConnectionStrings["minhaConexao"].ConnectionString);
            minhaConexao.Open();

            string select = "SELECT * FROM Aluno";
            SqlCommand selectCommand = new SqlCommand(select, minhaConexao);
            SqlDataReader sqlRead = selectCommand.ExecuteReader();


            List<Aluno> Alunos = new List<Aluno>();
            while (sqlRead.Read()) {
                Alunos.Add(new Aluno(int.Parse(sqlRead["IdAluno"].ToString()),
                                     sqlRead["Nome"].ToString(),
                                     int.Parse(sqlRead["RA"].ToString()),
                                     Convert.ToDateTime(sqlRead["DataNascimento"].ToString())));
            }
            return Alunos;
        }

        public static List<Aluno> listarAlunoPelaDisciplina(int idDisciplina) {
            SqlConnection minhaConexao = new SqlConnection(ConfigurationManager.ConnectionStrings["minhaConexao"].ConnectionString);
            minhaConexao.Open();

            string select = "select * from Aluno inner join AlunoDisciplina " +
                "on Aluno.IdAluno = AlunoDisciplina.IdAluno " +
                "where AlunoDisciplina.IdDisciplina = " + idDisciplina;
            SqlCommand selectCommand = new SqlCommand(select, minhaConexao);
            SqlDataReader sqlRead = selectCommand.ExecuteReader();


            List<Aluno> Alunos = new List<Aluno>();
            while (sqlRead.Read()) {
                Alunos.Add(new Aluno(int.Parse(sqlRead["IdAluno"].ToString()),
                                     sqlRead["Nome"].ToString(),
                                     int.Parse(sqlRead["RA"].ToString()),
                                     Convert.ToDateTime(sqlRead["DataNascimento"].ToString())));
            }
            return Alunos;
        }
    }
}

TecWeb/Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TecWeb.Models;

namespace TecWeb.Controllers {
    public class AlunoController : Controller {
        // GET: Aluno
        public ActionResult Index() {
           
            List<Aluno> Alunos = Aluno.listarAluno();

            //Alunos.Add(new Aluno(1, "Manuel", 123456, Convert.ToDateTime("12/12/2015")));
            //Alunos.Add(new Aluno(2, "Pedro", 14234123, Convert.ToDateTime("12/12/2010")));
            //Alunos.Add(new Aluno(3, "Miguel", 51234123, Convert.ToDateTime("12/12/2008")));
            //Alunos.Add(new Aluno(4, "Lucas", 12341234, Convert.ToDateTime("12/12/1990")));
            //Alunos.Add(new Aluno(5, "Vitor", 543545, Convert.ToDateTime("12/12/2020")));
            //Alunos.Add(new Aluno(6, "Rafael", 1235143, Convert.ToDateTime("12/12/2005")));


            return View(Alunos);
        }
    }
}

TecWeb/Controllers/DisciplinaController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TecWeb.Models;

namespace TecWeb.Controllers {
    public class DisciplinaController : Controller {
        // GET: Disciplina
        [HttpGet]
        public ActionResult Index(int idAluno, string nomeAluno) {
            //List<Disciplina> disciplina = new List<Disciplina>();

            ViewBag.idAluno = idAluno;
            ViewBag.nomeAluno = nomeAluno;


            //disciplina.Add(new Disciplina(1, 1, "Tecnologia Web", "5A", "SI"));
            //disciplina.Add(new Disciplina(1, 2, "Banco de Dados 1 ", "5A", "SI"));
            //disciplina.Add(new Disciplina(1, 3, "Banco de Dados 2", "1A", "SI"));

            //disciplina.Add(new Disciplina(2, 1, "Arquitetura de Computadores", "1A", "SI"));
            //disciplina.Add(new Disciplina(2, 2, "Arquitetura de Computadores", "1A", "SI"));
            //disciplina.Add(new Disciplina(2, 3, "Arquitetura de Computadores", "1A", "SI"));
            //disciplina.Add(new Disciplina(2, 4, "Arquitetura de Computadores", "1A", "SI"));

            //disciplina.Add(new Disciplina(3, 5, "Arquitetura de Computadores", "1A", "SI"));
            //disciplina.Add(new Disciplina(3, 6, "Arquitetura de Computadores", "1A", "SI"));

            //disciplina.Add(new Disciplina(4, 5, "Arquitetura de Computadores", "1A", "SI"));
            //disciplina.Add(new Disciplina(4, 6, "Arquitetura de Computadores", "1A", "SI"));

            //List<Disciplina> DisciplinasDeAluno = disciplina.Where(x => x.IdAluno == idAluno).ToList();
            
            List<Disciplina> disciplina = Disciplina.listarDisciplinaPeloAluno(idAluno);
            return View(disciplina);
        }

        [HttpPost]
        public ActionResult Index(int idAluno, int idDisciplina, string alunoNome) {
            string resultad = Disciplina.excluirVinculoDisciplinaAluno(idAluno, idDisciplina);
            @ViewBag.nomeAluno = alunoNome;
            List<Disciplina> disciplina = Disciplina.listarDisciplinaPeloAluno(idAluno);
            return View(disciplina);
        }

        public ActionResult buscarDisciplinas(String term) {

            return Json(Disciplina.buscaDisciplinas(term), JsonRequestBehavior.AllowGet);
        }

       public ActionResult disciplinas() {
            List<Disciplina> disciplina = Disciplina.listarDisciplina();
            return View(disciplina);
        }  

        public ActionResult novaDisciplina() {

            return View();
        }

        [HttpPost]
        public ActionResult novaDisciplina(string Nome, string Semestre, string Curso) {
            string sucesso = Disciplina.novaDisciplina(Nome, Semestre, Curso);
            ViewBag.sucesso = sucesso;

            return View();
        }
    }
}

TecWeb/Views/Aluno/Index.cshtml
@model List<Aluno>
@{
    ViewBag.Title = "Aluno";

}

<br />

        Aluno
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    @foreach (var aluno in @Model) {

        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingOne">
                <h4 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse_@aluno.IdAluno" aria-expanded="true" aria-controls="collapseOne">
                        @aluno.Nome
                    </a>
                </h4>
            </div>
            <div id="collapse_@aluno.IdAluno" class="panel-collapse collapse " role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body">
                    <label>RA: </label>@aluno.RA
                    <br />
                    <label>Data Nascimento: </label>@aluno.DataNascimento.ToString("dd/MM/yyyy")
                    <br />
                    <div class="panel-footer">
                        @*Disciplina/Index?idAluno=@aluno.IdAluno&nomeAluno=@aluno.Nome">@aluno.Nome*@
                        <a href="#" data-toggle="modal" data-target="#myModal"
                           onclick="loadDoc('@Url.Action("index","Disciplina", new { idAluno = @aluno.IdAluno, nomeAluno = @aluno.Nome })','GET')">
                            Disciplinas
                        </a>
                    </div>
                </div>
            </div>
        </div>



    }
</div>



<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Disciplinas</h4>
            </div>
            <div class="modal-body">
                <div id="demo"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>

            </div>
        </div>
    </div>
</div>